[contest]
name = "nhspc-test"
description = "nhspc-test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C++17 / g++", "Java / JDK", "Python 3 / CPython"]
[contest-config.mapping]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 3
memory_limit = 1024

[[tasks]]
name = "knapsack"
title = "A. 礦砂採集"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["0", "1"]

[[tasks]]
name = "village"
title = "B. 村莊與小徑"
time_limit = 1.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0", "1"]

[[tasks]]
name = "sample"
title = "C. 樣本解析"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "fruit"
title = "D. 包裝順序"
time_limit = 1.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "friend"
title = "E. 共同朋友"
time_limit = 2.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "delivery"
title = "F. 歡樂外送點"
time_limit = 2.3
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "matrix"
title = "G. 矩陣乘法"
time_limit = 6.5
  [tasks.inclusive_tests]
  3 = ["0", "1", "2"]

[[tasks]]
name = "mouse"
title = "H. 跑跑遊戲場"
time_limit = 0.1

[[tasks]]
name = "blackwhite"
title = "I. 黑白機"
time_limit = 1.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]
